# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Cache PlatformIO packages
      uses: actions/cache@v3
      id: PlatformIO_cache
      with:
        path: |
          /home/runner/.platformio/          
#          .pio
#        key: ${{ runner.os }}-build-${{ env.cache-name }}
        key: ${{ runner.os }}-platformio
        restore-keys: |
          ${{ runner.os }}-platformio 
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        check-latest: false
#        python-version: '3.x'
        # caching pip dependencies
 #       cache: 'pip' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        echo ~
    # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
    - name: Install platformIO libraries
#      run: pio pkg install
      run: pio pkg update
    - name: Run PlatformIO
      run: platformio run
    # Export 
    - name: Upload firmware.uf2
      uses: actions/upload-artifact@v4
      with:
        name: Firmware
        path: .pio/build/pico/firmware.uf2
        overwrite: true
    # - name: Commit changes
    #   run: |
    #     git config --global user.name "Dr. Paul Rounsavall"
    #     git config --global user.email "PaulRounsavall@yahoo.com"
    #     git add -f .pio/build/pico/firmware.uf2
    #     git commit -m "Update Firmware"
    #     git push
